version: '3.8'
services:
  web:
    build: .
    volumes:
      - ./www:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - APP_ENV=docker

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root  # Cambia esto por una contraseña segura
      MYSQL_DATABASE: db_restpro
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root  # Debe coincidir con la contraseña en MYSQL_ROOT_PASSWORD
    ports:
      - "8081:80"
    depends_on:
      - db

  ia:
    image: python:3.9  # Usa la versión de Python que necesites
    volumes:
      - ./ia:/app  # Mapea tu carpeta de scripts de Python
    working_dir: /app
    command: |
      bash -c "pip install -r requirements.txt && python app.py"  # Instalar dependencias y luego ejecutar la aplicación
    ports:
      - "8000:5000"  # Cambia el puerto según lo necesites

volumes:
  db_data:
