version: '3.8'
services:
  web:
    image: php:7.4-apache
    volumes:
      - ./www:/var/www/html
    ports:
      - "8080:80"

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root  
      MYSQL_DATABASE: db_restpro
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"

volumes:
  db_data:
