version: '3.8'
services:
  web:
    build: .
    volumes:
      - ./www:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - APP_ENV=docker

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root  # Cambia esto por una contraseña segura
      MYSQL_DATABASE: db_restpro
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root  # Debe coincidir con la contraseña en MYSQL_ROOT_PASSWORD
    ports:
      - "8081:80"
    depends_on:
      - db

  postgres_db:  # Nuevo servicio para PostgreSQL
    image: postgres:13
    environment:
      POSTGRES_USER: postgres_user  # Usuario de la base de datos
      POSTGRES_PASSWORD: postgres_password  # Contraseña de la base de datos
      POSTGRES_DB: api_db  # Base de datos específica para la API
    ports:
      - "5432:5432"  # Puerto por defecto de PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Volumen para persistencia de datos

  pgadmin:  # Opcional: Interfaz gráfica para gestionar PostgreSQL
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin  # Contraseña para pgAdmin
    ports:
      - "8082:80"
    depends_on:
      - postgres_db

  fastapi-api:
    build:
      context: ./fastapi-api  # Ruta del servicio FastAPI
    volumes:
      - ./fastapi-api:/app  # Mapea la carpeta de tu aplicación
    working_dir: /app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000  # Inicia FastAPI
    ports:
      - "8000:8000"  # Expone el puerto 8000

volumes:
  db_data:
  postgres_data:
