version: '3.8'
services:
  web:
    build: .
    volumes:
      - ./www:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - APP_ENV=docker

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ''  # Sin contraseña
      MYSQL_DATABASE: db_restpro
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ''  # Sin contraseña
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data:
